### PR TITLE
Added another CLI test and the first runner test

### PR DESCRIPTION
**Pull request by dread-pirate-johnny-spaceboots**
Is this what you had in mind for the test structure around the runner?

### CODE REVIEW

**Comment by maxim-zhao** [comment]
Merged but then I changed it a bit...

**Comment by johnny-spaceboots** [comment]
> Merged but then I changed it a bit...

Cool, had a look at your changes, I'll adopt that structure and asm comment format in subsequent PRs.

**Comment by johnny-spaceboots** [comment]
Good call on bumping up the cycles to just under what should be running, testing against a potential edge case certainly makes the test more valuable.

Semantically though I'm not a fan of it doing anything other than testing the exception piece (it going on to bump up the cycles and test that it executes in the expected cycle count), given it's name. But that's just me being nit-picky.

Just out of curiosity though, why prefer the exception assertion statement vs the [] line at the top of the method?

**Comment by maxim-zhao** [comment]
Most tests will test one thing only indeed, but often that means exercising it multiple times with different edge cases. So you will have multiple `Assert.<something>(...)` invocations. Decorating the function with a top level attribute has the same effect only when it's a one-liner test.

**Pull request merged**
